### ISSUE TITLE
How to use a branded domain or create a custom short URL?

### ISSUE THREAD

**Issue by ahmadawais** [specious/bitly-client#2]
I use a custom URL short name. That is ahmda.ws with Bitly. How can I use that?

**Comment by specious** [comment]
Have you tried `bitly-client --domain ahmda.ws <url>`?

**Comment by ahmadawais** [comment]
I did and it didn't work.

**Comment by ahmadawais** [comment]
OK, it seems to be working now. I can swear it was not working before 📦

**Comment by specious** [comment]
Hold on, now I'm interested.  When it wasn't working, how specifically did that look?  Was there an error message?  Silent failure?

**Comment by ahmadawais** [comment]
@specious I am pretty sure, I tried it with http://ahmda.ws
That didn't work instead brought history of bitlinks.

**Comment by ahmadawais** [comment]
@specious Would it be possible to define a custom URL? 
With Bitly's Chrome extension, you can do that. E.g. I created https://ahmda.ws/ME_2016 to my 2016 year in review.

**Comment by specious** [comment]
I think we'd need to implement the [user_save_custom_domain_keyword](https://dev.bitly.com/links.html#v3_user_save_custom_domain_keyword) API call.  The documentation states:

> This endpoint is only available to Bitly Enterprise customers.

**Comment by specious** [comment]
@ahmadawais, it's possible to create a custom keyword in the official web app.  What I've been doing:

```
$ bitly-client --domain j.mp "https://www.youtube.com/watch?v=2Jgb_DpaQhM"
http://j.mp/2hByc3O (https://www.youtube.com/watch?v=2Jgb_DpaQhM)

$ open http://j.mp/2hByc3O+
```

This opens the meta information page for the link in my browser and, if I'm logged into Bitly, I can click "Edit" and customize the link using the official web app:

![bitly-customize-link-keyword](https://user-images.githubusercontent.com/451178/31459271-ad8d8c42-ae90-11e7-8bad-50fef6c0f0ca.png)

**Comment by ahmadawais** [comment]
But that makes the CLI useless :(

**Comment by specious** [comment]
If you're an enterprise customer, you are eligible to use the [user_save_custom_domain_keyword](http://dev.bitly.com/links.html#v3_user_save_custom_domain_keyword) endpoint, as [officially clarified](https://groups.google.com/forum/#!topic/bitly-api/Ns4Z8bBT--4) by the director of application engineering at Bitly.

bitly-client doesn't make this function available, but bitly-client uses the Bitly API through @tanepiper's [node-bitly](https://github.com/tanepiper/node-bitly) library, which also doesn't currently expose that endpoint.

I think it's currently an open question how this functionality could be brought to bitly-client.

**Comment by specious** [comment]
See discussion #7 about migrating to a different implementation of the Bitly API layer.

**Comment by tanepiper** [comment]
@specious You can now do any request with node-bitly, I only provide some endpoints out of the box.

The README contains information on how to use `Bitly.bitlyRequest` to provide any options accepted by any endpoint.

**Comment by goodwid** [comment]
bitly-client could implement preferences for the user to configure, where one could set a default domain in the client and it would be used for domain generation in the absence of directives otherwise.
