### ISSUE TITLE
Escape invalid URI characters in expanded shortlink to create a valid URI

### ISSUE THREAD

**Issue by specious** [specious/bitly-client#4]
Currently, it is possible for an expanded link to be printed with a non-valid URI character. For example:
```
$ bitly-client http://bit.ly/10CK19i
http://bit.ly/10CK19i > http://www.gwern.net/Silk Road
```
The space should be replaced with e.g., `%20`.

See: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by haxzie** [comment]
This seems rather easier with `encodeURI`. Sending a PR :sparkles:

**Comment by specious** [comment]
Thank you so much. Just merged.
